# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - khi_ux150_arm_controller

  khi_ux150_arm_controller:
    type: FollowJointTrajectory
    joints:
      - jt1
      - jt2
      - jt3
      - jt4
      - jt5
      - jt6