controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


khi_ux150_controller:
  ros__parameters:
    type: khi_ux150_controller/RobotController
    joints:
      - joint_1
      - joint_2
      - joint_2_1
      - joint_3
      - joint_4
      - joint_5
      - joint_6

    command_interfaces:
      - position
      - velocity

    state_interfaces:
      - position
      - velocity
